import { z } from "zod";

export const createMedicineSchema = z.object({
  name: z.string().min(2, "Medicine name is required"),
  generic_name: z.string().optional(),
  dosage_form: z.enum([
    "Tablet",
    "Capsule",
    "Syrup",
    "Suspension",
    "Drops",
    "Injection",
    "Ointment",
    "Cream",
    "Gel",
    "Inhaler",
    "Rotacap",
    "Respules",
    "Mouthwash",
    "Powder",
    "Sachet",
    "Lotion",
    "Ear Drops",
    "Eye Drops",
    "Nasal Spray",
  ]),
  strength: z.string().optional(),
  default_frequency: z.string().optional(),
  default_timing: z.enum([
    "After Food",
    "Before Food",
    "With Food",
    "Empty Stomach",
    "At Bedtime",
    "As Needed (SOS)",
    "In the Morning",
  ]).optional(),
  default_duration_days: z.number().min(1).optional(),
  instructions: z.string().optional(),
});
